# Generated by Django 5.1.4 on 2025-01-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisCacheEntry',
            fields=[
                ('id', models.CharField(max_length=127, primary_key=True, serialize=False, unique=True)),
                ('partition_id', models.CharField(max_length=30)),
                ('data', models.JSONField(blank=True, null=True)),
                ('valid_until', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['partition_id'], name='cachemanage_partiti_d78654_idx')],
            },
        ),
    ]
