# Generated by Django 5.1.4 on 2025-01-05 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cachemanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysiscacheentry',
            options={'managed': False},
        ),
    ]
